server:
  port: 8088
  servlet:
    context-path: /shop-api
spring:
  application:
    name: shop-api
  datasource: # ????????
    type: com.zaxxer.hikari.HikariDataSource          # ??????HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql 版本大于5.7需要加cj
    url: jdbc:mysql://127.0.0.1:3306/wujiahao3
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # ????????????(??)?????????????????SQLException,??30?
      minimum-idle: 5                 # ?????
      maximum-pool-size: 20           # ?????
      auto-commit: true               # ????
      idle-timeout: 600000            # ?????????(??)???????(retired) ???10??
      pool-name: DateSourceHikariCP   # ?????
      max-lifetime: 1800000           # ???????(??)?????????????(retired),???30?? 1800000ms
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  data:
    redis:
      #redis?????(???0)
      database: 0
      #redis?????
      host: 127.0.0.1
      #redis???????
      port: 6379
      #redis????
      password: wu8321966

# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn




mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.shop_online.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: true # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)
